### ISSUE TITLE
 failed to perform operation on queue 'notifications.info' in vhost '/' due to timeout

### ISSUE THREAD

**Issue by lswadmin** [osism/documentation#459]
2023-02-16 16:32:37.271 1863728 ERROR oslo_messaging.notify.messaging [req-da4bceec-d012-4a55-8d50-ad8dd39b95b1 req-124ad8a2-137d-423c-bdda-7b5e9a6fb0fe 77a063acea284282968178bfb19e1c98 dfffdaac12704238a0b98d68006439c9 - default default] Could not send notification to notifications. Payload={'_context_domain': None, '_context_roles': [u'admin'], '_context_global_request_id': 'req-da4bceec-d012-4a55-8d50-ad8dd39b95b1', '_context_tenant_name': u'admin', 'event_type': 'security_group.create.end', '_context_request_id': 'req-124ad8a2-137d-423c-bdda-7b5e9a6fb0fe', 'timestamp': u'2023-02-16 08:31:34.153604', '_context_user': u'77a063acea284282968178bfb19e1c98', '_unique_id': '156a23a310494a46ae2a4b43a5e0a6d7', '_context_resource_uuid': None, '_context_tenant_id': u'dfffdaac12704238a0b98d68006439c9', '_context_is_admin_project': True, '_context_user_id': u'77a063acea284282968178bfb19e1c98', 'payload': {'security_group': {'description': u'anquan', 'tags': [], 'tenant_id': u'dfffdaac12704238a0b98d68006439c9', 'created_at': '2023-02-16T08:31:33Z', 'updated_at': '2023-02-16T08:31:34Z', 'security_group_rules': [{'direction': 'egress', 'protocol': None, 'description': None, 'tags': [], 'port_range_max': None, 'updated_at': '2023-02-16T08:31:34Z', 'revision_number': 0, 'id': u'6d2b4ef0-2f29-42ae-9be1-14ac1dc2eae2', 'remote_group_id': None, 'remote_ip_prefix': None, 'created_at': '2023-02-16T08:31:34Z', 'security_group_id': u'192b576d-01f4-48c6-a986-ba689362106c', 'tenant_id': u'dfffdaac12704238a0b98d68006439c9', 'port_range_min': None, 'ethertype': u'IPv6', 'project_id': u'dfffdaac12704238a0b98d68006439c9'}, {'direction': 'ingress', 'protocol': u'tcp', 'description': None, 'tags': [], 'port_range_max': 22, 'updated_at': '2023-02-16T08:31:34Z', 'revision_number': 0, 'id': u'9704aea8-d822-4192-950f-ce17a83091bc', 'remote_group_id': None, 'remote_ip_prefix': u'0.0.0.0/0', 'created_at': '2023-02-16T08:31:34Z', 'security_group_id': u'192b576d-01f4-48c6-a986-ba689362106c', 'tenant_id': u'dfffdaac12704238a0b98d68006439c9', 'port_range_min': 22, 'ethertype': u'IPv4', 'project_id': u'dfffdaac12704238a0b98d68006439c9'}, {'direction': 'ingress', 'protocol': u'tcp', 'description': None, 'tags': [], 'port_range_max': 80, 'updated_at': '2023-02-16T08:31:34Z', 'revision_number': 0, 'id': u'a209fb30-28bb-4e0c-b60c-d41a3f79899a', 'remote_group_id': None, 'remote_ip_prefix': u'0.0.0.0/0', 'created_at': '2023-02-16T08:31:34Z', 'security_group_id': u'192b576d-01f4-48c6-a986-ba689362106c', 'tenant_id': u'dfffdaac12704238a0b98d68006439c9', 'port_range_min': 80, 'ethertype': u'IPv4', 'project_id': u'dfffdaac12704238a0b98d68006439c9'}, {'direction': 'egress', 'protocol': None, 'description': None, 'tags': [], 'port_range_max': None, 'updated_at': '2023-02-16T08:31:33Z', 'revision_number': 0, 'id': u'b4e4d3b2-99bb-41cc-a137-ea3440c7b4ed', 'remote_group_id': None, 'remote_ip_prefix': None, 'created_at': '2023-02-16T08:31:33Z', 'security_group_id': u'192b576d-01f4-48c6-a986-ba689362106c', 'tenant_id': u'dfffdaac12704238a0b98d68006439c9', 'port_range_min': None, 'ethertype': u'IPv4', 'project_id': u'dfffdaac12704238a0b98d68006439c9'}, {'direction': 'ingress', 'protocol': u'icmp', 'description': None, 'tags': [], 'port_range_max': None, 'updated_at': '2023-02-16T08:31:34Z', 'revision_number': 0, 'id': u'bb05d535-97f3-492c-a28d-b76d50d09116', 'remote_group_id': None, 'remote_ip_prefix': u'0.0.0.0/0', 'created_at': '2023-02-16T08:31:34Z', 'security_group_id': u'192b576d-01f4-48c6-a986-ba689362106c', 'tenant_id': u'dfffdaac12704238a0b98d68006439c9', 'port_range_min': None, 'ethertype': u'IPv4', 'project_id': u'dfffdaac12704238a0b98d68006439c9'}], 'revision_number': 5, 'project_id': u'dfffdaac12704238a0b98d68006439c9', 'id': '192b576d-01f4-48c6-a986-ba689362106c', 'name': u'ttt_an'}}, '_context_project_name': u'admin', '_context_user_identity': u'77a063acea284282968178bfb19e1c98 dfffdaac12704238a0b98d68006439c9 - default default', '_context_auth_token': 'gAAAAABj7emn2vN3eSdXLIfQuoAeMJYcFkSZPgcdbzwrG7Z6hrC-ylZCYUKCCWUqDaO7SoMnelE76bwbjI6Z4tKzNtFoTYvpL_yC5ZJp0g3TYtycJ-PzCC5el875TlJ2c3p5p7NCOwgTc9yTAjU9l2PAzuoHunDkIxr1Nd-VfhGKGz0Cj8_I-mQ', '_context_show_deleted': False, '_context_tenant': u'dfffdaac12704238a0b98d68006439c9', 'priority': 'INFO', '_context_read_only': False, '_context_is_admin': True, '_context_project_id': u'dfffdaac12704238a0b98d68006439c9', '_context_project_domain': u'default', '_context_timestamp': '2023-02-16 08:30:31.777682', '_context_user_domain': u'default', '_context_user_name': u'admin', 'publisher_id': 'network.srv-tstack-con01', 'message_id': u'f278213f-ccd0-46df-ac53-40396f7e8bd3', '_context_project': u'dfffdaac12704238a0b98d68006439c9'}: MessageDeliveryFailure: Unable to connect to AMQP server on 10.1.11.5:5672 after None tries: Queue.declare: (404) NOT_FOUND - failed to perform operation on queue 'notifications.info' in vhost '/' due to timeout
2023-02-16 16:32:37.271 1863728 ERROR oslo_messaging.notify.messaging Traceback (most recent call last):
2023-02-16 16:32:37.271 1863728 ERROR oslo_messaging.notify.messaging   File "/usr/lib/python2.7/site-packages/oslo_messaging/notify/messaging.py", line 70, in notify
2023-02-16 16:32:37.271 1863728 ERROR oslo_messaging.notify.messaging     retry=retry)
2023-02-16 16:32:37.271 1863728 ERROR oslo_messaging.notify.messaging   File "/usr/lib/python2.7/site-packages/oslo_messaging/transport.py", line 140, in _send_notification
2023-02-16 16:32:37.271 1863728 ERROR oslo_messaging.notify.messaging     retry=retry)
2023-02-16 16:32:37.271 1863728 ERROR oslo_messaging.notify.messaging   File "/usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py", line 588, in send_notification
2023-02-16 16:32:37.271 1863728 ERROR oslo_messaging.notify.messaging     envelope=(version == 2.0), notify=True, retry=retry)
2023-02-16 16:32:37.271 1863728 ERROR oslo_messaging.notify.messaging   File "/usr/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py", line 552, in _send
2023-02-16 16:32:37.271 1863728 ERROR oslo_messaging.notify.messaging     conn.notify_send(exchange, target.topic, msg, retry=retry)
2023-02-16 16:32:37.271 1863728 ERROR oslo_messaging.notify.messaging   File "/usr/lib/python2.7/site-packages/oslo_messaging/_drivers/impl_rabbit.py", line 1292, in notify_send
2023-02-16 16:32:37.271 1863728 ERROR oslo_messaging.notify.messaging     exchange, msg, routing_key=topic, retry=retry)
2023-02-16 16:32:37.271 1863728 ERROR oslo_messaging.notify.messaging   File "/usr/lib/python2.7/site-packages/oslo_messaging/_drivers/impl_rabbit.py", line 1155, in _ensure_publishing
2023-02-16 16:32:37.271 1863728 ERROR oslo_messaging.notify.messaging     self.ensure(method, retry=retry, error_callback=_error_callback)
2023-02-16 16:32:37.271 1863728 ERROR oslo_messaging.notify.messaging   File "/usr/lib/python2.7/site-packages/oslo_messaging/_drivers/impl_rabbit.py", line 825, in ensure
2023-02-16 16:32:37.271 1863728 ERROR oslo_messaging.notify.messaging     raise exceptions.MessageDeliveryFailure(msg)
2023-02-16 16:32:37.271 1863728 ERROR oslo_messaging.notify.messaging MessageDeliveryFailure: Unable to connect to AMQP server on 10.1.11.5:5672 after None tries: Queue.declare: (404) NOT_FOUND - failed to perform operation on queue 'notifications.info' in vhost '/' due to timeout

**Comment by berendt** [comment]
Which service did this log come from?
