### ISSUE TITLE
MessageDeliveryFailure: Unable to connect to AMQP server on x.x.x.x:5672 after None tries: Queue.declare: (404) NOT_FOUND - failed to perform operation on queue 'versioned_notifications.info' in vhost '/' due to timeout

### ISSUE THREAD

**Issue by berendt** [osism/documentation#72]
```
2019-11-25 10:49:19.037 21 ERROR oslo_messaging.notify.messaging Traceback (most recent call last):
2019-11-25 10:49:19.037 21 ERROR oslo_messaging.notify.messaging   File "/var/lib/kolla/venv/local/lib/python2.7/site-packages/oslo_messaging/notify/messaging.py", line 70, in notify
2019-11-25 10:49:19.037 21 ERROR oslo_messaging.notify.messaging     retry=retry)
2019-11-25 10:49:19.037 21 ERROR oslo_messaging.notify.messaging   File "/var/lib/kolla/venv/local/lib/python2.7/site-packages/oslo_messaging/transport.py", line 140, in _send_notification
2019-11-25 10:49:19.037 21 ERROR oslo_messaging.notify.messaging     retry=retry)
2019-11-25 10:49:19.037 21 ERROR oslo_messaging.notify.messaging   File "/var/lib/kolla/venv/local/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py", line 588, in send_notification
2019-11-25 10:49:19.037 21 ERROR oslo_messaging.notify.messaging     envelope=(version == 2.0), notify=True, retry=retry)
2019-11-25 10:49:19.037 21 ERROR oslo_messaging.notify.messaging   File "/var/lib/kolla/venv/local/lib/python2.7/site-packages/oslo_messaging/_drivers/amqpdriver.py", line 552, in _send
2019-11-25 10:49:19.037 21 ERROR oslo_messaging.notify.messaging     conn.notify_send(exchange, target.topic, msg, retry=retry)
2019-11-25 10:49:19.037 21 ERROR oslo_messaging.notify.messaging   File "/var/lib/kolla/venv/local/lib/python2.7/site-packages/oslo_messaging/_drivers/impl_rabbit.py", line 1306, in notify_send
2019-11-25 10:49:19.037 21 ERROR oslo_messaging.notify.messaging     exchange, msg, routing_key=topic, retry=retry)
2019-11-25 10:49:19.037 21 ERROR oslo_messaging.notify.messaging   File "/var/lib/kolla/venv/local/lib/python2.7/site-packages/oslo_messaging/_drivers/impl_rabbit.py", line 1162, in _ensure_publishing
2019-11-25 10:49:19.037 21 ERROR oslo_messaging.notify.messaging     self.ensure(method, retry=retry, error_callback=_error_callback)
2019-11-25 10:49:19.037 21 ERROR oslo_messaging.notify.messaging   File "/var/lib/kolla/venv/local/lib/python2.7/site-packages/oslo_messaging/_drivers/impl_rabbit.py", line 832, in ensure
2019-11-25 10:49:19.037 21 ERROR oslo_messaging.notify.messaging     raise exceptions.MessageDeliveryFailure(msg)
2019-11-25 10:49:19.037 21 ERROR oslo_messaging.notify.messaging MessageDeliveryFailure: Unable to connect to AMQP server on x.x.x.x:5672 after None tries: Queue.declare: (404) NOT_FOUND - failed to perform operation on queue 'versioned_notifications.info' in vhost '/' due to timeout
```

**Comment by sinanejadebrahim** [comment]
it's 2021 ,we still have this issue and no fix.pls tell us if anyone finds the answer
❤️

**Comment by sharymo** [comment]
How did it work out?

**Comment by lswadmin** [comment]
i have the same problem
